export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_ERROR = 'FETCH_GAMES_ERROR';

export const FETCH_RUNS_REQUEST = 'FETCH_RUNS_REQUEST';
export const FETCH_RUNS_SUCCESS = 'FETCH_RUNS_SUCCESS';
export const FETCH_RUNS_ERROR = 'FETCH_RUNS_ERROR';